### ISSUE TITLE
KBS kustomize failures

### ISSUE THREAD

**Issue by mythi** [confidential-containers/trustee#361]
It's not possible to run

```
kubectl kustomize https://github.com/confidential-containers/trustee/kbs/config/kubernetes/overlays?ref=18c8ee378c6d83446ee635a702d5dee389028d8f
```

It'd be good to have it so that users could have their own `kustomization.yaml`s defined:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "https://github.com/confidential-containers/trustee/kbs/config/kubernetes/overlays?ref=18c8ee378c6d83446ee635a702d5dee389028d8f"
configMapGenerator:
...
secretGenerator:
```

with this, Kata tests would not have to `git clone` this repo.
