### ISSUE TITLE
KBS: session panic

### ISSUE THREAD

**Issue by ChengyuZhu6** [confidential-containers/trustee#374]
If multiple users send lots of `attest` http requests to KBS, it may result in session panic errors.

kbs logs: 
<img width="350" alt="session-panic" src="https://github.com/confidential-containers/trustee/assets/117246449/15a5f81d-6cf0-4822-aac7-88a76acd5977">

user logs:  
`[WARN] "/kbs/v0/attest": error sending request for url (http://localhost:8080/kbs/v0/attest): connection closed before message completed`

kbs config: 

```toml
sockets = ["0.0.0.0:8080"]
auth_public_key = "/opt/confidential-containers/kbs/user-keys/public.pub"
insecure_http = true

[attestation_token_config]
attestation_token_type = "CoCo"

[grpc_config]
as_addr = "http://as:50004"
```

cc @Xynnn007
