### ISSUE TITLE
KBS: Add 

### ISSUE THREAD

**Issue by davidhadas** [confidential-containers/trustee#382]
KBS API supports the following resource manipulation:
```
 /resource/{repository}/{type}/{tag}:
    get:
      operationId: getResource
      summary: Get a secret resource from the Key Broker Service.
       ... 
    post:
      operationId: registerSecretResource
      summary: Register a secret resource into the Key Broker Service.
      ...
```

This API is missing the option to delete resources that were added. 
Add:
```
delete:
      operationId: deleteSecretResource
      summary: Delete a secret resource from the Key Broker Service.
      parameters:
        - name: repository
          in: path
          description: A parent path of resource, can be empty to use the default repository.
          schema:
            type: string
          required: false
        - name: type
          in: path
          description: Resource type name
          schema:
            type: string
          required: true
        - name: tag
          in: path
          description: Resource instance tag
          schema:
            type: string
          required: true
```

Use Case: 
Under Peer-Pods Secure Comms, Keys are added to the KBS for each Peer Pod created. 
It is required to delete such keys once a Peer Pod is deleted.
